"""create operation analysis record tables

Revision ID: 42248f3f3230
Revises: 20260703_0002
Create Date: 2026-07-07 16:33:45.641646
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '42248f3f3230'
down_revision: str | Sequence[str] | None = '20260703_0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_ai_usage_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('analysis_record_id', sa.BigInteger(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('input_cost', sa.Float(precision=12, asdecimal=6), nullable=False),
    sa.Column('output_cost', sa.Float(precision=12, asdecimal=6), nullable=False),
    sa.Column('total_cost', sa.Float(precision=12, asdecimal=6), nullable=False),
    sa.Column('success', sa.SmallInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_ai_usage_record_analysis_record_id'), 'operation_ai_usage_record', ['analysis_record_id'], unique=False)
    op.create_index(op.f('ix_operation_ai_usage_record_model_name'), 'operation_ai_usage_record', ['model_name'], unique=False)
    op.create_index(op.f('ix_operation_ai_usage_record_trace_id'), 'operation_ai_usage_record', ['trace_id'], unique=False)
    op.create_index(op.f('ix_operation_ai_usage_record_user_id'), 'operation_ai_usage_record', ['user_id'], unique=False)
    op.create_table('operation_analysis_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('user_name', sa.String(length=128), nullable=True),
    sa.Column('report_name', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('analysis_mode', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('time_dimension', sa.String(length=32), nullable=True),
    sa.Column('analysis_date', sa.String(length=32), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('region_code', sa.String(length=64), nullable=True),
    sa.Column('page_context_json', sa.JSON(), nullable=True),
    sa.Column('input_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('abnormal_items_json', sa.JSON(), nullable=True),
    sa.Column('risk_items_json', sa.JSON(), nullable=True),
    sa.Column('advice_items_json', sa.JSON(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('final_answer_markdown', sa.Text(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('graph_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(precision=12, asdecimal=6), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cache_key', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_analysis_record_analysis_date'), 'operation_analysis_record', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_operation_analysis_record_cache_key'), 'operation_analysis_record', ['cache_key'], unique=False)
    op.create_index(op.f('ix_operation_analysis_record_domain'), 'operation_analysis_record', ['domain'], unique=False)
    op.create_index(op.f('ix_operation_analysis_record_status'), 'operation_analysis_record', ['status'], unique=False)
    op.create_index(op.f('ix_operation_analysis_record_trace_id'), 'operation_analysis_record', ['trace_id'], unique=True)
    op.create_table('operation_report_download_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_file_id', sa.BigInteger(), nullable=False),
    sa.Column('analysis_record_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('user_name', sa.String(length=128), nullable=True),
    sa.Column('download_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('download_status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_report_download_log_analysis_record_id'), 'operation_report_download_log', ['analysis_record_id'], unique=False)
    op.create_index(op.f('ix_operation_report_download_log_report_file_id'), 'operation_report_download_log', ['report_file_id'], unique=False)
    op.create_index(op.f('ix_operation_report_download_log_user_id'), 'operation_report_download_log', ['user_id'], unique=False)
    op.create_table('operation_report_file',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('analysis_record_id', sa.BigInteger(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('report_name', sa.String(length=255), nullable=False),
    sa.Column('report_format', sa.String(length=32), nullable=False),
    sa.Column('report_version', sa.Integer(), nullable=False),
    sa.Column('storage_type', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_url', sa.String(length=1024), nullable=True),
    sa.Column('object_key', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('generate_status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('last_download_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_report_file_analysis_record_id'), 'operation_report_file', ['analysis_record_id'], unique=False)
    op.create_index(op.f('ix_operation_report_file_generate_status'), 'operation_report_file', ['generate_status'], unique=False)
    op.create_index(op.f('ix_operation_report_file_report_format'), 'operation_report_file', ['report_format'], unique=False)
    op.create_index(op.f('ix_operation_report_file_trace_id'), 'operation_report_file', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_report_file_trace_id'), table_name='operation_report_file')
    op.drop_index(op.f('ix_operation_report_file_report_format'), table_name='operation_report_file')
    op.drop_index(op.f('ix_operation_report_file_generate_status'), table_name='operation_report_file')
    op.drop_index(op.f('ix_operation_report_file_analysis_record_id'), table_name='operation_report_file')
    op.drop_table('operation_report_file')
    op.drop_index(op.f('ix_operation_report_download_log_user_id'), table_name='operation_report_download_log')
    op.drop_index(op.f('ix_operation_report_download_log_report_file_id'), table_name='operation_report_download_log')
    op.drop_index(op.f('ix_operation_report_download_log_analysis_record_id'), table_name='operation_report_download_log')
    op.drop_table('operation_report_download_log')
    op.drop_index(op.f('ix_operation_analysis_record_trace_id'), table_name='operation_analysis_record')
    op.drop_index(op.f('ix_operation_analysis_record_status'), table_name='operation_analysis_record')
    op.drop_index(op.f('ix_operation_analysis_record_domain'), table_name='operation_analysis_record')
    op.drop_index(op.f('ix_operation_analysis_record_cache_key'), table_name='operation_analysis_record')
    op.drop_index(op.f('ix_operation_analysis_record_analysis_date'), table_name='operation_analysis_record')
    op.drop_table('operation_analysis_record')
    op.drop_index(op.f('ix_operation_ai_usage_record_user_id'), table_name='operation_ai_usage_record')
    op.drop_index(op.f('ix_operation_ai_usage_record_trace_id'), table_name='operation_ai_usage_record')
    op.drop_index(op.f('ix_operation_ai_usage_record_model_name'), table_name='operation_ai_usage_record')
    op.drop_index(op.f('ix_operation_ai_usage_record_analysis_record_id'), table_name='operation_ai_usage_record')
    op.drop_table('operation_ai_usage_record')
    # ### end Alembic commands ###
