"""add source_label to analysis_events

Revision ID: 786c07ec8ed1
Revises: f3380d72776e
Create Date: 2026-07-10 14:39:42.777464
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '786c07ec8ed1'
down_revision: str | Sequence[str] | None = 'f3380d72776e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_events', sa.Column('source_label', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_events', 'source_label')
    # ### end Alembic commands ###
