"""create runtime tables

Revision ID: 907e5e77381a
Revises: 20260702_0001
Create Date: 2026-07-03 15:38:38.316722
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '907e5e77381a'
down_revision: str | Sequence[str] | None = '20260702_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversation',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('biz_type', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversation_biz_type'), 'ai_conversation', ['biz_type'], unique=False)
    op.create_index(op.f('ix_ai_conversation_status'), 'ai_conversation', ['status'], unique=False)
    op.create_index(op.f('ix_ai_conversation_user_id'), 'ai_conversation', ['user_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_conversation_id'), 'ai_feedback', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_feedback_type'), 'ai_feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_ai_feedback_session_id'), 'ai_feedback', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_user_id'), 'ai_feedback', ['user_id'], unique=False)
    op.create_table('ai_prompt',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('scene_code', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uk_prompt_code_version')
    )
    op.create_index(op.f('ix_ai_prompt_code'), 'ai_prompt', ['code'], unique=False)
    op.create_index(op.f('ix_ai_prompt_scene_code'), 'ai_prompt', ['scene_code'], unique=False)
    op.create_index(op.f('ix_ai_prompt_status'), 'ai_prompt', ['status'], unique=False)
    op.create_table('ai_session',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_session_conversation_id'), 'ai_session', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_session_created_at'), 'ai_session', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_session_status'), 'ai_session', ['status'], unique=False)
    op.create_index(op.f('ix_ai_session_user_id'), 'ai_session', ['user_id'], unique=False)
    op.create_table('ai_trace',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=64), nullable=True),
    sa.Column('parent_span_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('span_type', sa.String(length=32), nullable=False),
    sa.Column('graph_name', sa.String(length=128), nullable=True),
    sa.Column('node_name', sa.String(length=128), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_code', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('cost_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_trace_conversation_id'), 'ai_trace', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_trace_created_at'), 'ai_trace', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_trace_session_id'), 'ai_trace', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_trace_span_type'), 'ai_trace', ['span_type'], unique=False)
    op.create_index(op.f('ix_ai_trace_status'), 'ai_trace', ['status'], unique=False)
    op.create_index(op.f('ix_ai_trace_trace_id'), 'ai_trace', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_trace_trace_id'), table_name='ai_trace')
    op.drop_index(op.f('ix_ai_trace_status'), table_name='ai_trace')
    op.drop_index(op.f('ix_ai_trace_span_type'), table_name='ai_trace')
    op.drop_index(op.f('ix_ai_trace_session_id'), table_name='ai_trace')
    op.drop_index(op.f('ix_ai_trace_created_at'), table_name='ai_trace')
    op.drop_index(op.f('ix_ai_trace_conversation_id'), table_name='ai_trace')
    op.drop_table('ai_trace')
    op.drop_index(op.f('ix_ai_session_user_id'), table_name='ai_session')
    op.drop_index(op.f('ix_ai_session_status'), table_name='ai_session')
    op.drop_index(op.f('ix_ai_session_created_at'), table_name='ai_session')
    op.drop_index(op.f('ix_ai_session_conversation_id'), table_name='ai_session')
    op.drop_table('ai_session')
    op.drop_index(op.f('ix_ai_prompt_status'), table_name='ai_prompt')
    op.drop_index(op.f('ix_ai_prompt_scene_code'), table_name='ai_prompt')
    op.drop_index(op.f('ix_ai_prompt_code'), table_name='ai_prompt')
    op.drop_table('ai_prompt')
    op.drop_index(op.f('ix_ai_feedback_user_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_session_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_feedback_type'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_conversation_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_ai_conversation_user_id'), table_name='ai_conversation')
    op.drop_index(op.f('ix_ai_conversation_status'), table_name='ai_conversation')
    op.drop_index(op.f('ix_ai_conversation_biz_type'), table_name='ai_conversation')
    op.drop_table('ai_conversation')
    # ### end Alembic commands ###
