"""create analysis_events table

Revision ID: f3380d72776e
Revises: 20260708_0003
Create Date: 2026-07-08 23:10:50.775547
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'f3380d72776e'
down_revision: str | Sequence[str] | None = '20260708_0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=True),
    sa.Column('node_name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('event_timestamp', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_analysis_events_run_sequence')
    )
    op.create_index(op.f('ix_analysis_events_created_at'), 'analysis_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_events_event_id'), 'analysis_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_analysis_events_run_id'), 'analysis_events', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_events_run_id'), table_name='analysis_events')
    op.drop_index(op.f('ix_analysis_events_event_id'), table_name='analysis_events')
    op.drop_index(op.f('ix_analysis_events_created_at'), table_name='analysis_events')
    op.drop_table('analysis_events')
    # ### end Alembic commands ###
